# frozen_string_literal: true

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

begin
  ruby_version = File.read(File.expand_path('../.ruby-version', __dir__)).strip
  ruby_version = ruby_version.sub(/^ruby-/, '')
  ruby ruby_version
rescue Errno::ENOENT
  # Fallback: do not constrain ruby if file missing
end

source "https://rubygems.org"

gem "sinatra", "~> 4.0"
gem "puma", "~> 6.5"
gem "dotenv", "~> 3.1"
gem "fast-mcp", "~> 1.5"
gem "faraday", "~> 2.10"
gem "activerecord", "~> 8.0"
gem "pg", "~> 1.5"

group :development, :test do
  gem "rerun", "~> 0.14" # autoreload
  gem "rspec", "~> 3.13"
  gem "rack-test", "~> 2.1"
  gem "webmock", "~> 3.23"
end
