name: Branch CI

on:
  push:
    branches-ignore:
      - main

jobs:
  backend-tests:
    name: RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
        # Note: Do not use shell line-continuation backslashes here; the entire string is passed directly to `docker create`.
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      RAILS_ENV: test
      HIVEMIND_DB_HOST: localhost
      HIVEMIND_DB_USER: postgres
      HIVEMIND_DB_PASSWORD: password
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libpq-dev
      - name: Prepare database
        run: |
          bin/rails db:create db:schema:load
      - name: Run RSpec
        run: |
          bin/rails spec

  ui-lint:
    name: ESLint (UI)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint

  ui-tests:
    name: Vitest (UI)
    runs-on: ubuntu-latest
    needs: ui-lint
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run Vitest
        run: npm test -- --reporter=dot

  aggregate:
    runs-on: ubuntu-latest
    needs: [backend-tests, ui-lint, ui-tests]
    steps:
      - name: Success
        run: echo "All checks passed."
